# 경로 설정 파일 참조
project_config: "project_config.yaml"

# 기본 설정
full:
  start: 2020
  end: 2025
  output_file: "${config.data.full}"
  max_workers: 4
  skip: false

# 최신 데이터만 빠르게
sample:
  start: 2024
  end: 2024
  output_file: "${config.data.sample}"
  max_workers: 2
  skip: false